### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by gemarcano** [lab11/M-ulator#23]
It looks like the python scripts used for building assume that `python` is aliased to `python2`. As python2 is now no longer supported, we should consider moving away from it and towards `python3`. I'm going to try to see if I can port the python scripts over.

**Comment by ppannuto** [comment]
Mhmm, yeah, I'd forgotten about the ppb generation stuff. It's probably a bit silly to build that every time instead of just generating it once, but hopefully something that's relatively easy to update nonetheless. 

I didn't really know about ARM's CMSIS stuff when I first wrote this (in 2012!), but in the long view, it would likely be better to replace this with one of the CMSIS libraries, but that's a much more substantial project. I suspect `2to3` should just work on this file.

**Comment by gemarcano** [comment]
Interesting, I also wasn't aware of CMSIS. I'll take a look.

In the meantime, PR #24 should fix this particular issue.

**Comment by gemarcano** [comment]
#24 has been merged. Next time I'll add a message to the commit saying it fixes issue X so it gets closed automatically.
